### ISSUE TITLE
Quest: Fumping, Terrokkar Forest.

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#96] opened 2016-06-23 14:14 UTC
The Quest given to you by Dwarfowitz in Terrokar that tells you to bump and rump a drum around the Bone Wastes ;) is not working as intended, I can easily live with getting sand gnomes nine out of ten times, but when the mob that I need, actually appears I'd like to be able to kill it.

The Mature Bone Sifter appears in all it's glory, it begins to attack me and my pet but I'm not allowed to target it and kill it back.

**Comment by Oriden** [comment] 2016-06-27 23:16
Duplicate of #56, closing.

**Closed by Oriden** 2016-06-27 23:16 UTC
