### ISSUE TITLE
[Quest] Get to Getry

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#290] opened 2016-08-24 13:17 UTC
http://www.wow-mania.com/armory/?quest=11703

Players have to talk to Shadowstalker Getry (http://www.wow-mania.com/armory/?npc=25729) at Warsong Farms. 

The NPC is not where he is supposed to be up a tower, instead he is on the ground near Varidus the Flenser (http://www.wow-mania.com/armory/?npc=25618)

The quest cannot be handed in as Getry does not have a ? over his head. This is not working as intended. 

See also https://github.com/wow-mania/Redemption/issues/291 as it is the follow up quest.

**Comment by wow-mania** [comment] 2016-08-24 15:20
![image](https://cloud.githubusercontent.com/assets/12248683/17936405/9b13dbb2-6a16-11e6-9b8d-988d147b054c.png)

Seems to be working OK

**Comment by Calebrimbor** [comment] 2016-08-24 15:33
That's odd, I've tested it just a minute ago and despite Shadowstalker Getry is friendly, and I've completed the whole chain, it doesn't allow to interact with him. Reopening the issue.

![wowscrnshot_082416_173105](https://cloud.githubusercontent.com/assets/20358867/17936890/931c7fae-6a20-11e6-8e3c-0c9b1bd093f8.jpg)

![nieuwe bitmapafbeelding 2](https://cloud.githubusercontent.com/assets/20358867/17936960/d069f1e8-6a20-11e6-9cd1-ea3e1880f171.png)

**Comment by Calebrimbor** [comment] 2016-08-24 15:35
That's odd, I've just tested it a few minutes ago after closing this issue, despite I've done all the pre-quests and he's friendly it doesn't allow me to interact with him

![wowscrnshot_082416_173105](https://cloud.githubusercontent.com/assets/20358867/17937056/24b0b1d8-6a21-11e6-8210-66f583090a66.jpg)

![nieuwe bitmapafbeelding 2](https://cloud.githubusercontent.com/assets/20358867/17937072/2c3e2818-6a21-11e6-8ad3-b640179d73f9.png)

**Comment by Calebrimbor** [comment] 2016-08-25 22:14
Issue still persists with the exact same malfunction. Reopened the issue.

**Comment by Calebrimbor** [comment] 2016-08-26 09:13
Confimed as fixed!

**Comment by GMLucetta** [comment] 2016-08-29 21:18
Issue still persists with the exact same malfunction. Reopened the issue.

**Comment by Calebrimbor** [comment] 2016-09-03 22:50
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Closed by Calebrimbor** 2016-09-03 22:50 UTC
