### ISSUE TITLE
[Quest] Filling the Cages

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#295] opened 2016-08-26 09:42 UTC
http://www.wow-mania.com/armory/?quest=11984

Players have to use Bounty Hunter's Cage (http://www.wow-mania.com/armory/?item=35736) in order to capture a Live Ice Troll (http://www.wow-mania.com/armory/?npc=26444)

The Ice Troll continues to attack even when it is captured in the cage. Players can work around this by running away or killing the troll, but it is not working as intended. Quest is doable but needs some tweaks.

**Comment by wow-mania** [comment] 2016-08-29 17:09
Will be fixed for next update this Wednesday.

**Comment by Calebrimbor** [comment] 2016-09-03 11:12
Quest is fixed, the only tweak left to do is, once the Trolls are caged they shouldn't deal or receive damage. The troll died since I had a DoT on him, but the objective was complete. I tried on a Drakkari Shaman (http://www.wow-mania.com/armory/?npc=26447)

**Comment by Calebrimbor** [comment] 2016-09-06 21:32
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Closed by Calebrimbor** 2016-09-06 21:32 UTC
Labels: Fixed
