### ISSUE TITLE
[Quest] Foolish Endeavors

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#291] opened 2016-08-24 13:22 UTC
http://www.wow-mania.com/armory/?quest=11705

Due to issues with the previous quest in the chain Get to Getry (http://www.wow-mania.com/armory/?quest=117030) (https://github.com/wow-mania/Redemption/issues/290)

The NPC Shadowstalker Getry (http://www.wow-mania.com/armory/?npc=25729) is not on his tower so cannot walk down starting the dialogue necessary before the player has to help him kill Varidus the Flenser (http://www.wow-mania.com/armory/?npc=25618) so the quest cannot be completed. 

This is not working as intended.

**Comment by wow-mania** [comment] 2016-08-24 15:24
![image](https://cloud.githubusercontent.com/assets/12248683/17936463/ce4532f6-6a16-11e6-9b93-1f73ab40b81f.png)

![image](https://cloud.githubusercontent.com/assets/12248683/17936590/2e358f4e-6a17-11e6-9656-ca418b64cc1b.png)


Looks like it is working

**Comment by Calebrimbor** [comment] 2016-08-24 15:39
This is odd, I've tested it as soon as you closed it, and I'm not able to interact with Shadowstalker Getry. I think this NPC still needs some fixing.

**Comment by Calebrimbor** [comment] 2016-08-25 22:14
Issue still persists with the exact same malfunction. Reopened the issue.

**Comment by wow-mania** [comment] 2016-08-25 22:58
Please try it in Elysium. It may be a reset issue.

**Comment by Calebrimbor** [comment] 2016-08-26 09:14
Confirmed as fixed

**Comment by GMLucetta** [comment] 2016-08-29 21:19
Issue still persists with the exact same malfunction. Reopened the issue.

**Comment by Calebrimbor** [comment] 2016-09-03 22:50
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Closed** 2016-09-04 18:30 UTC
