### ISSUE TITLE
maul problem (druid bear form)

### ISSUE THREAD

**Issue by Radghar** [wow-mania/Redemption#398] opened 2016-10-08 20:32 UTC
the ability maul (bear form) doesn't work correctly. After few seconds i press it the spell works and does damage

**Comment by genasi** [comment] 2016-10-10 10:48
Thats how maul is supposed to work, it boosts the damage from your normal attack and isnt an ability of its own.

**Comment by Kalasbyxan** [comment] 2016-10-10 21:59
Working as intended at 3.3.5 where the damage is applied onto the next melee attack. Closing.

**Closed by Kalasbyxan** 2016-10-10 21:59 UTC
