### ISSUE TITLE
[Quest]: The Frost Wyrm and its Master

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#413] opened 2015-08-19 15:33 UTC
The quest item to bring Glacion down to fight does not work at the platform like it should. The quest item think you aren't at the proper location even when you are. Possible the marker for that area is place wrong.

**Comment by wow-mania** [comment] 2015-08-20 10:26
Duplicate of 206. Please search before entering new issues.

**Closed by wow-mania** 2015-08-20 10:26 UTC
