### ISSUE TITLE
ROLL BACK 

### ISSUE THREAD

**Issue by Bugreports** [wow-mania/Redemption#554] opened 2015-09-01 11:08 UTC
Roll Back on Professions and Tyrael "sorry i can't do much about it " YEAH ,but i lost mats and i find myself with a problem, cuz i had saved my mats for doing on one row, Check loggs of my time please and fixt it... really annoying 
I was awake for training the Jewelcrafting skill at 3AM ,i think 2 AM server time.... and i lost like 4 hours of game ..... NOT COOL

The rollbacks are so annoying ... if u know what i mean

**Comment by fvicaria** [comment] 2015-09-01 11:21
That was an issue that should be resolved in a better way. Contact Janitor in game for this cases. This is not a bug.

**Closed by fvicaria** 2015-09-01 11:21 UTC
